### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lord420123** [MCCTeam/Minecraft-Console-Client#2118]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

1.19 - donno if that's the latest

### Expected Behavior

I log in, and join the sub-server, everything gets executed correctly, and nothing further happens.

### Actual Behavior

I log in, and join the sub-server, everything gets executed correctly, and, the console client immediately crashes

### Steps to Reproduce the bug

1. Join 'said' server
2. Join 'said' sub-server
3. should crash, then and there.

### Attach screenshot here (If applicable)

https://prnt.sc/pzybK_v5aJB6 - the only screenshot I've got.

### Anythings that could help diagnosing the bug

```txt
I'm honestly really confused myself, it randomly just bugged out and crashed, but then after I'd taken some time to research the error and tried debugging, it randomly started to work again(meaning, currently, there're no issues).
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

boxpvpv.minehut.gg

**Comment by Lord420123** [comment]
It seems, with some further' "playing around" with the settings, it's currently working fine for me, with no errors whatsoever. I even lost a very specific issue(which I made a workaround for - hence why I didn't mention it).

**Comment by milutinke** [comment]
@BruceChenQAQ Seems like a problem with terrain handling, specifically with `SetBlock` in `World.cs`
Was it changed in 1.19?

**Comment by milutinke** [comment]
> It seems, with some further' "playing around" with the settings, it's currently working fine for me, with no errors whatsoever. I even lost a very specific issue(which I made a workaround for - hence why I didn't mention it).

For now you can use my fork: https://github.com/milutinke/Minecraft-Console-Client/tree/inventory-entity-terrain-handling-1.19
The issue should be fixed.
Tho you need to build it yourself.
Follow the instructions from: https://mccteam.github.io/docs/guide/installation.html
But when cloning a repository, do this command instead the one from wiki:
```bash
git clone https://github.com/milutinke/Minecraft-Console-Client/ --recursive -b inventory-entity-terrain-handling-1.19
```

**Comment by BruceChenQAQ** [comment]
> @BruceChenQAQ Seems like a problem with terrain handling, specifically with `SetBlock` in `World.cs` Was it changed in 1.19?

This is probably because the dimensional data is not handled correctly when switching worlds, perhaps it would be better to change the default value of dimensional data in 1.18 and above.

It is also possible that after receiving the Respawn packet for switching world or dimension, you still get the BlockChange packet of the original world, because the maximum height of these two worlds is different, and there is an out-of-bounds error

**Comment by milutinke** [comment]
> > @BruceChenQAQ Seems like a problem with terrain handling, specifically with `SetBlock` in `World.cs` Was it changed in 1.19?
> 
> This is probably because the dimensional data is not handled correctly when switching worlds, perhaps it would be better to change the default value of dimensional data in 1.18 and above.
> 
> It is also possible that after receiving the Respawn packet for switching world or dimension, you still get the BlockChange packet of the original world, because the maximum height of these two worlds is different, and there is an out-of-bounds error

Can you fork my branch and try to fix it, I have no idea how the terrain handling functions.

**Comment by BruceChenQAQ** [comment]
Switching between different versions of servers may cause exceptions in chunk data processing, trying to fix it
